package youngfriend.gui;

import java.io.File;
import java.util.List;

import javax.swing.JOptionPane;

import youngfriend.utils.ConfigIO;
import youngfriend.utils.InvokerServiceUtils;
import youngfriend.utils.ServiceConfig;

/**
 * 
 * @author czj
 */
public class ServiceConnectSetPnl extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;

	private boolean ok;

	public ServiceConnectSetPnl() {
		initComponents();
		initParameter();
	}

	private void initParameter() {
		ServiceConfig config = new ServiceConfig();
		config.getServiceConnectPara();
		String address = config.getServiceAdd();
		String port = config.getServicePort();

		List addressList = config.getAddressList();

		String serviceAdd = "";
		if (address != null && !"".equals(address)) {
			serviceAdd = serviceAdd + address;
		}
		if (port != null && !"".equals(port)) {
			serviceAdd = serviceAdd + ":" + port;
		}

		int index = 0;
		for (int i = 0; i < addressList.size(); i++) {
			Cmb_IP.addItem(addressList.get(i).toString());
			if (address.equals(addressList.get(i).toString()))
				index = i;
		}

		if (Cmb_IP.getItemCount() == 0)
			Cmb_IP.addItem("127.0.0.1");

		Cmb_IP.setSelectedIndex(index);
		jTextField2.setText(port);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel1.setBounds(6, 6, 366, 83);
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setBounds(24, 14, 78, 16);
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setBounds(59, 53, 43, 16);
		jTextField2 = new javax.swing.JTextField();
		jTextField2.setBounds(108, 47, 216, 28);
		Cmb_IP = new javax.swing.JComboBox();
		Cmb_IP.setBounds(103, 8, 221, 27);
		jButton1 = new javax.swing.JButton();
		jButton1.setBounds(108, 101, 75, 29);
		jButton2 = new javax.swing.JButton();
		jButton2.setBounds(196, 101, 75, 29);

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel1.setText("服务器地址："); // NOI18N

		jLabel2.setText("端 口："); // NOI18N

		jTextField2.setText("12345"); // NOI18N

		Cmb_IP.setEditable(true);
		Cmb_IP.setToolTipText("");
		Cmb_IP.setName("Cmb_IP");

		Cmb_IP.getAccessibleContext().setAccessibleName("");

		jButton1.setText("登录"); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("退出"); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		setLayout(null);
		add(jButton1);
		add(jButton2);
		add(jPanel1);
		jPanel1.setLayout(null);
		jPanel1.add(jLabel2);
		jPanel1.add(jLabel1);
		jPanel1.add(jTextField2);
		jPanel1.add(Cmb_IP);
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO 将在此处添加您的处理代码：
		String address = Cmb_IP.getSelectedItem().toString();
		String port = jTextField2.getText();

		ServiceConfig config = new ServiceConfig();
		config.setServiceAdd(address);
		config.setServicePort(port);
		ConfigIO.saveConfigFile("service", config, "1");

		// 将服务地址加到内存中
		try {
			InvokerServiceUtils.getAndSetService("http://" + address + ":" + port);
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(this, e.getMessage());
			return;
		}
		// if(this.mainframe!=null)
		// this.mainframe.getMainpnl().reflushTree(true);
		setOk(true);
		javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO 将在此处添加您的处理代码：
		setOk(false);
		javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
	}// GEN-LAST:event_jButton2ActionPerformed

	// 目录是否存在
	public void checkCreatDir(String dirPath) {
		File file = new File(dirPath);
		if (!file.exists()) {
			file.mkdirs();
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox Cmb_IP;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextField2;

	// End of variables declaration//GEN-END:variables

	/**
	 * @return the ok
	 */
	public boolean isOk() {
		return ok;
	}

	/**
	 * @param ok
	 *            the ok to set
	 */
	public void setOk(boolean ok) {
		this.ok = ok;
	}

}
